PolicyManagement/Models/Policy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace PolicyManagement.Models
{
    public class Policy
    {
        [Key]
        public int PolicyId { get; set; }
        [Display(Name = "Policy Title")]
        public string PTitle { get; set; }
        [Display(Name = "Policy Description")]
        public string PDescription { get; set; }
        [Display(Name = "Scope and Responsibilities")]
        public string PScope { get; set; }
        public ICollection<Procedure> Procedures { get; set; }
        [Display(Name = "Approval Authority")]
        public string ApprovalAuthority { get; set; }
        [Display(Name = "Advisory Committee")]
        public string AdvisoryCommittee { get; set; }
        public string Administrator { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Next Review Date")]
        public DateTime NxtReviewDate { get; set; }
        [Display(Name = "Original Approval Authority")]
        public string OrigApprAuth { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Approval Date")]
        public DateTime ApprDate { get; set; }
        [Display(Name = "Amendment Authority")]
        public string AmendAuth { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Amendment Date")]
        public DateTime AmendDate { get; set; }
        public string Notes { get; set; }
    }
}

PolicyManagement/Controllers/PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PolicyManagement.Models;

namespace PolicyManagement.Controllers
{
    public class PolicyController : Controller
    {
        private readonly PolicyWorkflowContext _context;

        public PolicyController(PolicyWorkflowContext context)
        {
            _context = context;
        }

        // GET: Policy
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter) //int? page
        {
            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["ApprovalSortParm"] = String.IsNullOrEmpty(sortOrder) ? "app_desc" : "";
            ViewData["ReviewSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            //if(searchString != null)
            //{
            //    page = 1;
            //}
            //else
            //{
            //    searchString = currentFilter;
            //}

            ViewData["CurrentFilter"] = searchString;

            //var policies = from p in _context.Policies select p;

            var policies =  from p in _context.Policies.Include(i => i.Procedures).ThenInclude(i=>i.Processes).ThenInclude(i=>i.Actions) select p;

            if(!String.IsNullOrEmpty(searchString))
            {
                policies = policies.Where(p => p.PTitle.Contains(searchString) || p.PDescription.Contains(searchString));
            }

            switch(sortOrder)
            {
                case "title_desc": policies = policies.OrderByDescending(p => p.PTitle);
                    break;
                case "app_desc": policies = policies.OrderByDescending(p => p.ApprovalAuthority);
                    break;
                case "date_desc": policies = policies.OrderByDescending(p => p.NxtReviewDate);
                    break;
                default:
                    policies = policies.OrderBy(p => p.PTitle);
                    break;

            }
            //return View(await PaginatedList<Policy>.CreateAsync(policies.AsNoTracking(), page ?? 1, pageSize));
            return View(await policies.ToListAsync());
        }

        //GET: Policy/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policy = await _context.Policies.Include(i => i.Procedures).ThenInclude(i => i.Processes).ThenInclude(i => i.Actions)
                .SingleOrDefaultAsync(m => m.PolicyId == id);
            if (policy == null)
            {
                return NotFound();
            }

            return View(policy);
        }

        // GET: Policy/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Policy/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PolicyId,PTitle,PDescription,PScope,ApprovalAuthority,AdvisoryCommittee,Administrator,NxtReviewDate,OrigApprAuth,ApprDate,AmendAuth,AmendDate,Notes")] Policy policy)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(policy);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(DbUpdateException ex)
            {
                Console.WriteLine(ex);
                ModelState.AddModelError("", "Unable to save changes. Please try again");
            }
            
            return View(policy);
        }

        // GET: Policy/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policy = await _context.Policies.SingleOrDefaultAsync(m => m.PolicyId == id);
            if (policy == null)
            {
                return NotFound();
            }
            return View(policy);
        }

        // POST: Policy/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PolicyId,PTitle,PDescription,PScope,ApprovalAuthority,AdvisoryCommittee,Administrator,NxtReviewDate,OrigApprAuth,ApprDate,AmendAuth,AmendDate,Notes")] Policy policy)
        {
            if (id != policy.PolicyId)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(policy);
                    await _context.SaveChangesAsync();                       
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PolicyExists(policy.PolicyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. Try again.");
                        throw;

                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(policy);
        }

        // GET: Policy/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policy = await _context.Policies
                .SingleOrDefaultAsync(m => m.PolicyId == id);
            if (policy == null)
            {
                return NotFound();
            }

            return View(policy);
        }

        // POST: Policy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var policy = await _context.Policies.SingleOrDefaultAsync(m => m.PolicyId == id);
            _context.Policies.Remove(policy);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PolicyExists(int id)
        {
            return _context.Policies.Any(e => e.PolicyId == id);
        }
    }
}

PolicyManagement/Controllers/ProcedureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PolicyManagement.Models;

namespace PolicyManagement.Controllers
{
    public class ProcedureController : Controller
    {
        private readonly PolicyWorkflowContext _context;

        public ProcedureController(PolicyWorkflowContext context)
        {
            _context = context;
        }

        // GET: Procedure
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            //ViewData["PolicySortParm"] = String.IsNullOrEmpty(sortOrder) ? "policy_desc" : "Number";

            var procedures = from pr in _context.Procedures.Include(q => q.Policy)  select pr;

            switch (sortOrder)
            {
                case "title_desc": procedures =  procedures.OrderByDescending(p => p.PrTitle);
                    break;
                //case "policy_desc": procedures = procedures.OrderByDescending(p => p.PolicyId);
                //    break;
                default:
                    procedures = procedures.OrderBy(p => p.PrTitle);
                    break;
            }
            
            //var policyWorkflowContext = _context.Procedures.Include(p => p.Policy);
            return View(await procedures.AsNoTracking().ToListAsync());
        }

        // GET: Procedure/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var procedure = await _context.Procedures
                .Include(p => p.Policy)
                .SingleOrDefaultAsync(m => m.ProcedureId == id);
            if (procedure == null)
            {
                return NotFound();
            }

            return View(procedure);
        }

        // GET: Procedure/Create
        public IActionResult Create()
        {
            //ViewData["PolicyTitle"] = new SelectList(_context.Policies, "PolicyId", "PTitle");
            //ViewData["PolicyId"] = new SelectList(_context.Policies, "PolicyId", "PolicyId");
            PopulatePolicyDropdownList();
            return View();
        }

        // POST: Procedure/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProcedureId,PrTitle,PrDesc,PrPurpose,PolicyId")] Procedure procedure)
        {
            if (ModelState.IsValid)
            {
                _context.Add(procedure);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            PopulatePolicyDropdownList(procedure.PolicyId);
            //ViewData["PolicyTitle"] = new SelectList(_context.Policies, "PolicyId", "PTitle", procedure.PolicyId);
            //ViewData["PolicyId"] = new SelectList(_context.Policies, "PolicyId", "PolicyId", procedure.PolicyId);
            return View(procedure);
        }

        // GET: Procedure/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var procedure = await _context.Procedures.SingleOrDefaultAsync(m => m.ProcedureId == id);
            if (procedure == null)
            {
                return NotFound();
            }
            //ViewData["PolicyId"] = new SelectList(_context.Policies, "PolicyId", "PolicyId", procedure.PolicyId);
            PopulatePolicyDropdownList(procedure.PolicyId);
            return View(procedure);
        }

        // POST: Procedure/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProcedureId,PrTitle,PrDesc,PrPurpose,PolicyId")] Procedure procedure)
        {
            if (id != procedure.ProcedureId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(procedure);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProcedureExists(procedure.ProcedureId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["PolicyId"] = new SelectList(_context.Policies, "PolicyId", "PolicyId", procedure.PolicyId);
            PopulatePolicyDropdownList(procedure.PolicyId);
            return View(procedure);
        }

        // GET: Procedure/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var procedure = await _context.Procedures
                .Include(p => p.Policy)
                .SingleOrDefaultAsync(m => m.ProcedureId == id);
            if (procedure == null)
            {
                return NotFound();
            }

            return View(procedure);
        }

        // POST: Procedure/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var procedure = await _context.Procedures.SingleOrDefaultAsync(m => m.ProcedureId == id);
            _context.Procedures.Remove(procedure);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProcedureExists(int id)
        {
            return _context.Procedures.Any(e => e.ProcedureId == id);
        }

        private void PopulatePolicyDropdownList(object selectedPolicy = null)
        {
            var policiesQuery = from p in _context.Policies orderby p.PTitle select p;

            ViewBag.PolicyId = new SelectList(policiesQuery.AsNoTracking(), "PolicyId", "PTitle", selectedPolicy);
        }
    }
}

PolicyManagement/Views/Policy/Create.cshtml
@model PolicyManagement.Models.Policy

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Create a Policy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PTitle" class="control-label"></label>
                <input asp-for="PTitle" class="form-control" />
                <span asp-validation-for="PTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PDescription" class="control-label"></label>
                <input asp-for="PDescription" class="form-control" />
                <span asp-validation-for="PDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PScope" class="control-label"></label>
                <input asp-for="PScope" class="form-control" />
                <span asp-validation-for="PScope" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApprovalAuthority" class="control-label"></label>
                <input asp-for="ApprovalAuthority" class="form-control" />
                <span asp-validation-for="ApprovalAuthority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdvisoryCommittee" class="control-label"></label>
                <input asp-for="AdvisoryCommittee" class="form-control" />
                <span asp-validation-for="AdvisoryCommittee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Administrator" class="control-label"></label>
                <input asp-for="Administrator" class="form-control" />
                <span asp-validation-for="Administrator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NxtReviewDate" class="control-label"></label>
                <input asp-for="NxtReviewDate" class="form-control" />
                <span asp-validation-for="NxtReviewDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrigApprAuth" class="control-label"></label>
                <input asp-for="OrigApprAuth" class="form-control" />
                <span asp-validation-for="OrigApprAuth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApprDate" class="control-label"></label>
                <input asp-for="ApprDate" class="form-control" />
                <span asp-validation-for="ApprDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmendAuth" class="control-label"></label>
                <input asp-for="AmendAuth" class="form-control" />
                <span asp-validation-for="AmendAuth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmendDate" class="control-label"></label>
                <input asp-for="AmendDate" class="form-control" />
                <span asp-validation-for="AmendDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PolicyManagement/Views/Policy/Delete.cshtml
@model PolicyManagement.Models.Policy

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>Policy</h4>*@
    <hr />
    <dl>
        @* class="dl-horizontal" *@
        <dt>
            @Html.DisplayNameFor(model => model.PTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PTitle)
        </dd><br/>
        <dt>
            @Html.DisplayNameFor(model => model.PDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PDescription)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.PScope)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PScope)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.ApprovalAuthority)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApprovalAuthority)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.AdvisoryCommittee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AdvisoryCommittee)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.Administrator)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Administrator)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.NxtReviewDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NxtReviewDate)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.OrigApprAuth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrigApprAuth)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.ApprDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApprDate)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.AmendAuth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmendAuth)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.AmendDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmendDate)
        </dd><br />
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd><br />
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="PolicyId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a class="btn btn-default" asp-action="Index">Back to List</a>
    </form>
</div>

PolicyManagement/Views/Policy/Details.cshtml
@model PolicyManagement.Models.Policy

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Policy</h4>
    @*<div class="col-md-push-10">
            <a asp-action="Create" asp-controller="Procedure" class="btn btn-primary">Create a procedure</a>
        </div>*@
    <hr />
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.PTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PTitle)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.PDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PDescription)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.PScope)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PScope)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <br />
        <table class="table table-bordered">
            <thead><b>Approval and Review</b></thead>
            <tbody>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ApprovalAuthority)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.ApprovalAuthority)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.AdvisoryCommittee)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.AdvisoryCommittee)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Administrator)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.Administrator)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NxtReviewDate)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.NxtReviewDate)
                    </td>
                </tr>
            </tbody>
        </table>
        <br />
        <table class="table table-bordered">
            <thead><b>Approval and Amendment History</b></thead>
            <tbody>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.OrigApprAuth)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.OrigApprAuth)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ApprDate)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.ApprDate)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.AmendAuth)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.AmendAuth)
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.AmendDate)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.AmendDate)
                    </td>
                </tr>
            </tbody>
        </table>

        <br />
        <dt>@Html.DisplayNameFor(model => model.Procedures)</dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Procedure Title</th>
                    <th>Procedure Description</th>
                    <th>Procedure Purpose</th>
                </tr>
                @foreach (var item in Model.Procedures)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PrTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PrDesc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PrPurpose)
                        </td>
                    </tr>
                }
            </table>
        </dd>
        <br />
        <dt>@Html.DisplayNameFor(model => model.Procedures.FirstOrDefault().Processes)</dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Process Title</th>
                    <th>Process Description</th>

                </tr>
                @foreach (var item in Model.Procedures.FirstOrDefault().Processes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProcTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProcDesc)
                        </td>

                    </tr>
                }
            </table>
        </dd>
        <br />
        <dt>@Html.DisplayNameFor(model => model.Procedures.FirstOrDefault().Processes.FirstOrDefault().Actions)</dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Action Title</th>
                    <th>Action Description</th>
                    <th>Action Inputs</th>
                    <th>Action Outputs</th>
                    <th>Departments</th>
                    <th>Is SRS Affected</th>

                </tr>
                @foreach (var item in Model.Procedures.FirstOrDefault().Processes.FirstOrDefault().Actions)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ATitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ADesc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Inputs)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Outputs)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Departments)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsSRSAffected)
                        </td>

                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PolicyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>